//
//  PeopleView.m
//  Bezel
//
//  Created by John Clem on 8/12/14.
//  Copyright (c) 2014 learnswift. All rights reserved.
//

#import "PeopleView.h"

@implementation PeopleView

- (void)drawRect:(CGRect)rect {
    
    //// Frames
    CGRect frame = rect;
    
    
    //// Bezier Drawing
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.99551 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81223 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.99328 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80989 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.99077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81375 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.99296 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80929 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88499 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75133 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.97713 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77983 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92581 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76729 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.81381 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72088 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.86168 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74222 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.83725 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73151 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70705 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67403 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77890 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70504 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68548 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66701 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66232 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69164 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66875 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66886 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64700 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62953 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65657 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65527 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65183 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63886 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64643 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62863 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63143 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59674 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64750 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62976 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62885 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59491 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62454 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59369 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62977 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59556 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62732 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59456 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62227 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59369 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62566 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54479 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57557 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62101 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54707 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65941 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45430 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64381 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53591 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65763 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47461 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68647 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45240 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65941 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45430 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67762 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48103 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70087 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37091 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69531 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42378 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69217 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39904 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70218 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31253 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70968 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34245 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72103 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30481 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69304 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30472 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31878 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69112 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31253 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68321 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13296 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69588 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29313 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20050 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71032 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13447 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13474 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71032 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13447 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68839 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12978 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70344 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13379 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69604 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13211 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74431 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13031 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.71989 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13393 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74431 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13031 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68776 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11588 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72763 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13018 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12418 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71931 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11831 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70596 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11866 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71931 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11831 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64736 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08966 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69734 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11612 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66898 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10216 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02681 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58283 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03402 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.50242 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01989 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02519 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02681 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.50192 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01525 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02865 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02519 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44618 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00372 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49220 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00096 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02865 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.42583 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00281 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35594 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06467 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49220 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00096 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37364 * CGRectGetWidth(frame), CGRectGetMinY(frame) + -0.01289 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29755 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09908 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35594 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06467 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31790 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06584 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32940 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08682 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.29755 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09908 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32055 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07944 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28717 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18469 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32940 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08682 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.28540 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11175 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30374 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32134 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.28894 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25763 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.29666 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31395 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28158 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34996 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30374 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32134 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.26716 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30992 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30005 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.29693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39264 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.29882 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39706 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32940 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46538 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30144 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44265 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31525 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47922 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36391 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54386 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32940 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46538 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34621 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53462 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59368 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.37482 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54955 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37472 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57367 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36563 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59368 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36455 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59673 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36504 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59445 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.36463 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59542 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34676 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62952 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35992 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60672 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.35651 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62295 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.33342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64826 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34084 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63351 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.33670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64399 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27781 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67872 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31604 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67086 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30601 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66948 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11990 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74898 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.22031 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69756 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.17018 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72773 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.05317 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77475 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.09666 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75880 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.07153 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76383 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.00309 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81457 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.04017 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78248 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.00560 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80429 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.00086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86872 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + -0.00215 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83604 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.00086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84300 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.00086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93333 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.00086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89457 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.00086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90418 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93333 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32263 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93333 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93333 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89683 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91537 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91478 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.99551 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81223 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.99455 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86649 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 1.00038 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83536 * CGRectGetHeight(frame))];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;
    
    [[UIColor blackColor] setFill];
    [bezierPath fill];
    
    
}

@end
